"use client";
import { useState } from "react";
import { supabase } from "@/lib/supabase";
import { useApp } from "@/context/AppContext";

export default function TeacherDashboard() {
  const { profile } = useApp();
    
      // States for student generation
        const [email, setEmail] = useState("");
          const [password, setPassword] = useState("");
            const [fullName, setFullName] = useState("");
              const [instrument, setInstrument] = useState("Clarinet");
                const [status, setStatus] = useState("new recruit");

                  // States for file uploads
                    const [tuneTitle, setTuneTitle] = useState("");
                      const [audioFile, setAudioFile] = useState(null);

                        if (!profile || profile.role !== 'teacher') return <p className="p-8 text-red-400">Unauthorized Access.</p>;

                          // Provision authentication for student
                            const handleCreateStudent = async (e) => {
                                e.preventDefault();
                                    const { error } = await supabase.auth.signUp({
                                          email,
                                                password,
                                                      options: { data: { full_name: fullName, instrument, status, role: 'student' } }
                                                          });
                                                              if (error) alert(error.message);
                                                                  else { alert("Student Created and Authenticated Successfully!"); setEmail(""); setPassword(""); setFullName(""); }
                                                                    };

                                                                      // Upload MP3 Audio File safely to storage bucket
                                                                        const handleUploadTune = async (e) => {
                                                                            e.preventDefault();
                                                                                if (!audioFile) return;

                                                                                    const fileExt = audioFile.name.split('.').pop();
                                                                                        const fileName = `${Math.random()}.${fileExt}`;
                                                                                            
                                                                                                // 1. Upload raw audio binary directly to cloud storage
                                                                                                    let { error: uploadError } = await supabase.storage.from('band-tunes').upload(fileName, audioFile);
                                                                                                        if (uploadError) return alert(uploadError.message);

                                                                                                            // 2. Resolve target public web url
                                                                                                                const { data: { publicUrl } } = supabase.storage.from('band-tunes').getPublicUrl(fileName);

                                                                                                                    // 3. Write metadata to tracking table
                                                                                                                        const { error: dbError } = await supabase.from('tunes').insert({ title: tuneTitle, audio_url: publicUrl, uploaded_by: profile.id });
                                                                                                                            if (dbError) alert(dbError.message);
                                                                                                                                else { alert("Tune published!"); setTuneTitle(""); setAudioFile(null); }
                                                                                                                                  };

                                                                                                                                    return (
                                                                                                                                        <div className="space-y-12">
                                                                                                                                              <header className="border-b border-slate-800 pb-4">
                                                                                                                                                      <h1 className="text-3xl font-black text-emerald-400">Al Jamea Band — Teacher Studio</h1>
                                                                                                                                                              <p className="text-slate-400">Welcome, {profile.full_name}</p>
                                                                                                                                                                    </header>

                                                                                                                                                                          <div className="grid md:grid-cols-2 gap-8">
                                                                                                                                                                                  {/* Provision Section */}
                                                                                                                                                                                          <form onSubmit={handleCreateStudent} className="bg-slate-900 p-6 rounded-xl border border-slate-800 space-y-4">
                                                                                                                                                                                                    <h2 className="text-xl font-bold border-b border-slate-800 pb-2">Assign Student Authentication</h2>
                                                                                                                                                                                                              <input type="text" placeholder="Full Name" value={fullName} onChange={e=>setFullName(e.target.value)} className="w-full p-2 rounded bg-slate-800 border border-slate-700 text-white" required />
                                                                                                                                                                                                                        <input type="email" placeholder="Email Address" value={email} onChange={e=>setEmail(e.target.value)} className="w-full p-2 rounded bg-slate-800 border border-slate-700 text-white" required />
                                                                                                                                                                                                                                  <input type="password" placeholder="Temporary Password" value={password} onChange={e=>setPassword(e.target.value)} className="w-full p-2 rounded bg-slate-800 border border-slate-700 text-white" required />
                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                      <div className="grid grid-cols-2 gap-4">
                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                <label className="text-xs text-slate-400 block mb-1">Instrument</label>
                                                                                                                                                                                                                                                                                              <select value={instrument} onChange={e=>setInstrument(e.target.value)} className="w-full p-2 rounded bg-slate-800 border border-slate-700">
                                                                                                                                                                                                                                                                                                              <option value="Clarinet">Clarinet</option>
                                                                                                                                                                                                                                                                                                                              <option value="Saxophone">Saxophone</option>
                                                                                                                                                                                                                                                                                                                                              <option value="Trumpet">Trumpet</option>
                                                                                                                                                                                                                                                                                                                                                              <option value="Percussion">Percussion</option>
                                                                                                                                                                                                                                                                                                                                                                            </select>
                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                  <label className="text-xs text-slate-400 block mb-1">Status Classification</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                <select value={status} onChange={e=>setStatus(e.target.value)} className="w-full p-2 rounded bg-slate-800 border border-slate-700">
                                                                                                                                                                                                                                                                                                                                                                                                                                                <option value="new recruit">New Recruit</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <option value="member">Member</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button type="submit" className="w-full py-2 font-bold bg-blue-600 hover:bg-blue-500 rounded text-white transition">Deploy Student Credentials</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Media Uploads Section */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <form onSubmit={handleUploadTune} className="bg-slate-900 p-6 rounded-xl border border-slate-800 space-y-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h2 className="text-xl font-bold border-b border-slate-800 pb-2">Publish New MP3 Audio Tune</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <input type="text" placeholder="Tune Title" value={tuneTitle} onChange={e=>setTuneTitle(e.target.value)} className="w-full p-2 rounded bg-slate-800 border border-slate-700 text-white" required />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <label className="text-xs text-slate-400 block mb-1">Target MP3 File Only</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input type="file" accept="audio/mp3" onChange={e=>setAudioFile(e.target.files[0])} className="w-full text-slate-400 file:mr-4 file:py-2 file:px-4 file:rounded file:border-0 file:bg-slate-800 file:text-slate-200 hover:file:bg-slate-700" required />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button type="submit" className="w-full py-2 font-bold bg-emerald-600 hover:bg-emerald-500 rounded text-slate-950 transition">Push MP3 to Student Cloud</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    